# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collector.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Collector.CollectRequest" do
  end
  add_message "Collector.CollectReply" do
    optional :message, :string, 1
  end
end

module Collector
  CollectRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("Collector.CollectRequest").msgclass
  CollectReply = Google::Protobuf::DescriptorPool.generated_pool.lookup("Collector.CollectReply").msgclass
end
